# Generated by Django 5.1.6 on 2025-03-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamScape', '0002_occasion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('event_type', models.CharField(choices=[('wedding', 'Wedding'), ('party', 'Party'), ('conference', 'Conference')], max_length=50)),
                ('date', models.DateField()),
                ('guests', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='', max_length=20)),
                ('lname', models.CharField(default='', max_length=20)),
                ('email', models.CharField(default='', max_length=20)),
                ('mobile', models.CharField(default='', max_length=20)),
                ('address', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('eventname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('date', models.DateField(blank=True)),
                ('mobile', models.CharField(max_length=200)),
                ('altmobile', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=100)),
                ('description', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Occasion',
        ),
    ]
