# Generated by Django 5.1.6 on 2025-04-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamScape', '0003_booking_user_userevents_delete_event_delete_occasion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
