# Generated by Django 5.1.6 on 2025-04-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamScape', '0004_event_delete_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='confirmpassword',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
    ]
