# Generated by Django 5.1.6 on 2025-04-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamScape', '0005_rename_address_user_confirmpassword_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmpassword',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='fname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='lname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
