# Generated by Django 5.1.6 on 2025-04-12 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamScape', '0006_alter_user_confirmpassword_alter_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=100)),
                ('status', models.CharField(default='Success', max_length=50)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DreamScape.userevents')),
            ],
        ),
    ]
