# Generated by Django 5.1.6 on 2025-04-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamScape', '0008_rename_transaction_id_payment_txn_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
