# Generated by Django 5.1.6 on 2025-04-21 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamScape', '0009_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevents',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DreamScape.user'),
        ),
    ]
